/* THE SYSTEM: Side Missions + Full-Screen Boss Battles */
const SIDE_SYSTEM_KEY='systemMission:sideBossV3';
const BUILD_STATS=['Strength','Endurance','Conditioning','Mobility','Consistency','Recovery'];
const TRAINING_PATHS={
 Balanced:{label:'Balanced',desc:'Build every attribute evenly.',boost:[]},
 'Fat Loss':{label:'Fat Loss',desc:'Prioritize conditioning and endurance while preserving strength.',boost:['Conditioning','Endurance']},
 'Muscle Building':{label:'Muscle Building',desc:'Prioritize strength-focused resistance training and recovery.',boost:['Strength','Recovery']},
 Strength:{label:'Strength',desc:'Prioritize force production while maintaining a complete build.',boost:['Strength','Consistency']},
 Endurance:{label:'Endurance',desc:'Prioritize sustained work capacity and conditioning.',boost:['Endurance','Conditioning']}
};
const RANK_STANDARDS={D:{Strength:10,Endurance:10,Conditioning:10,Mobility:8,Consistency:10,Recovery:8},C:{Strength:20,Endurance:20,Conditioning:20,Mobility:16,Consistency:20,Recovery:16},B:{Strength:35,Endurance:35,Conditioning:35,Mobility:30,Consistency:40,Recovery:30},A:{Strength:50,Endurance:50,Conditioning:50,Mobility:42,Consistency:55,Recovery:42},S:{Strength:65,Endurance:65,Conditioning:65,Mobility:55,Consistency:70,Recovery:55},'S+':{Strength:78,Endurance:78,Conditioning:78,Mobility:68,Consistency:82,Recovery:68},Shadow:{Strength:88,Endurance:88,Conditioning:88,Mobility:80,Consistency:92,Recovery:80}};
function loadBuild(){let b={};try{b=JSON.parse(localStorage.getItem('systemPlayerBuildV1')||'{}')}catch(e){}b.path=b.path||'Balanced';b.stats=b.stats||{};BUILD_STATS.forEach(x=>b.stats[x]=Number(b.stats[x]||0));return b}
function saveBuild(b){localStorage.setItem('systemPlayerBuildV1',JSON.stringify(b))}
function setTrainingPath(path){if(!TRAINING_PATHS[path])return;const b=loadBuild();b.path=path;saveBuild(b);if(typeof addSystemMessage==='function')addSystemMessage('TRAINING PATH UPDATED: '+path+'. Your rank, XP and history are unchanged.','level');renderPlayerStatus();renderSideSystem()}
function pathBonus(path,stat){return (TRAINING_PATHS[path]?.boost||[]).includes(stat)?1:0}
function buildDay(){return today()}
function classifyTraining(name){const n=String(name||'').toLowerCase();if(/stretch|mobility|yoga|flex/.test(n))return['Mobility','Recovery'];if(/run|walk|bike|cardio|row|swim|endurance/.test(n))return['Endurance','Conditioning'];if(/circuit|hiit|conditioning/.test(n))return['Conditioning','Endurance'];if(/rest|recovery/.test(n))return['Recovery','Consistency'];return['Strength','Consistency']}
function awardBuildTraining(name,duration,intensity){const b=loadBuild(),day=buildDay();b.daily=b.daily||{};if(b.daily.date!==day)b.daily={date:day,points:0};const cap=8,remaining=Math.max(0,cap-b.daily.points);if(!remaining)return;const pts=Math.min(remaining,Math.max(1,Math.round((Number(duration)||10)/15))*Math.max(1,Math.min(2,Number(intensity)||1)));const stats=classifyTraining(name),basePrimary=Math.ceil(pts*.7),baseSecondary=pts-basePrimary,primary=basePrimary+pathBonus(b.path,stats[0]),secondary=baseSecondary+pathBonus(b.path,stats[1]);b.stats[stats[0]]=Math.min(100,b.stats[stats[0]]+primary);b.stats[stats[1]]=Math.min(100,b.stats[stats[1]]+secondary);b.daily.points+=pts;saveBuild(b);if(typeof addSystemMessage==='function')addSystemMessage('BUILD GROWTH: '+stats[0]+' +'+primary+(secondary?' • '+stats[1]+' +'+secondary:'')+' ('+b.daily.points+'/'+cap+' daily points)','quest');renderSideSystem()}
function awardBuildMission(id){const b=loadBuild(),map={walk20:['Endurance','Conditioning'],hydrate:['Recovery','Consistency'],protein:['Recovery','Consistency'],core50:['Strength','Conditioning'],mobility:['Mobility','Recovery'],weekend:['Consistency','Endurance']},stats=map[id];if(!stats)return;b.stats[stats[0]]=Math.min(100,b.stats[stats[0]]+2);b.stats[stats[1]]=Math.min(100,b.stats[stats[1]]+1);saveBuild(b)}
window.SystemBuild={awardTraining:awardBuildTraining,awardMission:awardBuildMission,getBuild:loadBuild,setPath:setTrainingPath};
function weakestStats(rank){const b=loadBuild(),req=RANK_STANDARDS[rank]||{},missing=BUILD_STATS.map(x=>({stat:x,value:b.stats[x],need:req[x]||0,gap:(req[x]||0)-b.stats[x]})).filter(x=>x.gap>0).sort((a,z)=>z.gap-a.gap);return missing}
function buildEligible(rank){return weakestStats(rank).length===0}
function correctiveMission(rank){const w=weakestStats(rank)[0];if(!w)return null;const map={Strength:'Complete a strength-focused training session.',Endurance:'Complete 20+ minutes of steady endurance work.',Conditioning:'Complete a full-body conditioning circuit.',Mobility:'Complete 15 minutes of mobility work.',Consistency:'Complete your scheduled training sessions this week.',Recovery:'Complete a recovery session and prioritize rest.'};return{stat:w.stat,desc:map[w.stat],gap:w.gap}}
const RANK_REWARDS={
 E:{label:'AWAKENED',desc:'Core daily Side Missions'},
 D:{label:'HUNTER',desc:'Challenge Missions unlocked',bonus:10},
 C:{label:'VETERAN',desc:'Advanced Missions + 15% Side Mission XP',bonus:15},
 B:{label:'ELITE',desc:'Elite Missions + 20% Side Mission XP',bonus:20},
 A:{label:'MASTER',desc:'Master Missions + 25% Side Mission XP',bonus:25},
 S:{label:'S-RANK',desc:'S-Rank Missions + 35% Side Mission XP',bonus:35},
 'S+':{label:'NATIONAL LEVEL',desc:'National-Level Missions + 45% Side Mission XP',bonus:45},
 Shadow:{label:'SOVEREIGN',desc:'Sovereign Missions + 60% Side Mission XP',bonus:60}
};
const RANK_MISSIONS=[
 {id:'challenge100',rank:'D',title:'Hunter Challenge',desc:'Complete 100 total bodyweight reps.',xp:80},
 {id:'cardio25',rank:'C',title:'Veteran Endurance',desc:'Complete 25 minutes of continuous cardio.',xp:100},
 {id:'eliteCircuit',rank:'B',title:'Elite Circuit',desc:'Complete 4 rounds of a full-body circuit.',xp:125},
 {id:'masterMobility',rank:'A',title:'Master Control',desc:'Complete 20 minutes of mobility plus core work.',xp:150},
 {id:'sRankSession',rank:'S',title:'S-Rank Session',desc:'Complete a challenging 45-minute training session.',xp:200},
 {id:'nationalTrial',rank:'S+',title:'National-Level Mission',desc:'Complete 60 minutes of combined strength and conditioning.',xp:275},
 {id:'sovereignTrial',rank:'Shadow',title:'Sovereign Mission',desc:'Complete your hardest safe full-body session of the week.',xp:350}
];
const SIDE_MISSIONS=[
{id:'walk20',title:'Extra Mile',desc:'Walk for 20 minutes outside your scheduled workout.',xp:50},
{id:'hydrate',title:'Hydration Mission',desc:'Hit your daily water target.',xp:25},
{id:'protein',title:'Protein Protocol',desc:'Hit your daily protein target.',xp:25},
{id:'core50',title:'Core Assault',desc:'Complete 50 total core reps.',xp:40},
{id:'mobility',title:'Recovery Mission',desc:'Complete 10 minutes of stretching or mobility.',xp:30},
{id:'weekend',title:'Weekend Warrior',desc:'Complete an extra Saturday or Sunday workout.',xp:75}
];
function task(text,damage,attack,seconds=0){return{text,damage,attack,seconds}}
function variants(sq,pu,lu,pl,cardio){return[
{name:'Strength Trial',focus:'Strength / Core',time:(cardio+10)+'–'+(cardio+18)+' min',tasks:[task(sq+' squats',30,'POWER STRIKE'),task(pu+' push-ups',30,'POWER STRIKE'),task(lu+' alternating lunges',15,'LEG BREAK'),task(pl+'-second plank',15,'CORE BREAK',pl),task(cardio+'-minute cardio',10,'ENDURANCE HIT',cardio*60)]},
{name:'Endurance Trial',focus:'Endurance / Conditioning',time:(cardio+12)+'–'+(cardio+20)+' min',tasks:[task(Math.max(10,sq-5)+' squats',10,'POWER HIT'),task(Math.max(5,pu-3)+' push-ups',10,'POWER HIT'),task((lu+6)+' step-ups',20,'ENDURANCE STRIKE'),task(Math.round(pl*1.15)+'-second plank',20,'CORE BREAK',Math.round(pl*1.15)),task((cardio+3)+'-minute cardio',40,'ENDURANCE CRITICAL',(cardio+3)*60)]},
{name:'Full Body Trial',focus:'Full Body / Control',time:(cardio+10)+'–'+(cardio+18)+' min',tasks:[task(sq+' chair or bodyweight squats',20,'STRIKE'),task(pu+' incline or standard push-ups',20,'STRIKE'),task(lu+' reverse lunges',20,'STRIKE'),task(Math.max(10,Math.round(sq/2))+' glute bridges',20,'STRIKE'),task(cardio+'-minute cardio',20,'STRIKE',cardio*60)]},
{name:'System Circuit',focus:'Circuit / Conditioning',time:(cardio+8)+'–'+(cardio+16)+' min',tasks:[task('3 rounds: '+Math.ceil(sq/3)+' squats',15,'COMBO HIT'),task('3 rounds: '+Math.ceil(pu/3)+' push-ups',20,'COMBO HIT'),task('3 rounds: '+Math.ceil(lu/3)+' alternating lunges',25,'HEAVY COMBO'),task('3 rounds: '+Math.ceil(pl/3)+'-second plank',15,'CORE BREAK'),task(Math.max(5,cardio-5)+'-minute cardio finisher',25,'FINISHER',Math.max(5,cardio-5)*60)]}
]}
const BOSS_STAGES=[
{rank:'D',level:10,title:'D-Rank Promotion',reward:250,variants:variants(20,10,20,30,10)},
{rank:'C',level:20,title:'C-Rank Promotion',reward:400,variants:variants(30,15,24,45,12)},
{rank:'B',level:30,title:'B-Rank Promotion',reward:600,variants:variants(40,20,30,60,15)},
{rank:'A',level:40,title:'A-Rank Promotion',reward:850,variants:variants(50,25,36,75,18)},
{rank:'S',level:50,title:'S-Rank Promotion',reward:1200,variants:variants(60,30,40,90,20)},
{rank:'S+',level:70,title:'National-Level Trial',reward:1600,variants:variants(70,35,50,120,25)},
{rank:'Shadow',level:90,title:'Sovereign Trial',reward:2500,variants:variants(80,40,60,120,30)}
];
let bossClock=null,bossTimer=null,battleStartedAt=0;
function today(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function loadSideSystem(){let s={};try{s=JSON.parse(localStorage.getItem(SIDE_SYSTEM_KEY)||'{}')}catch(e){}if(s.date!==today())s={...s,date:today(),completed:[]};s.completed=s.completed||[];s.boss=s.boss||{};return s}
function saveSideSystem(s){localStorage.setItem(SIDE_SYSTEM_KEY,JSON.stringify(s))}
function currentClass(s){let c='E';for(const b of BOSS_STAGES)if(s.boss[b.rank]?.passed)c=b.rank;return c}
function rankIndex(rank){return ['E','D','C','B','A','S','S+','Shadow'].indexOf(rank)}
function unlockedMissions(s){const ci=rankIndex(currentClass(s));return SIDE_MISSIONS.concat(RANK_MISSIONS.filter(m=>rankIndex(m.rank)<=ci))}
function rewardXp(base,s){const r=RANK_REWARDS[currentClass(s)]||RANK_REWARDS.E;return Math.round(base*(1+(r.bonus||0)/100))}
function bossIndex(rank){return BOSS_STAGES.findIndex(b=>b.rank===rank)}
function eligible(b,s){const i=bossIndex(b.rank),level=typeof state!=='undefined'?state.level:1;return level>=b.level&&(i===0||!!s.boss[BOSS_STAGES[i-1].rank]?.passed)&&buildEligible(b.rank)}
function chooseVariant(b,e){let n=Math.floor(Math.random()*b.variants.length);if(b.variants.length>1&&n===e.lastVariant)n=(n+1+Math.floor(Math.random()*(b.variants.length-1)))%b.variants.length;return n}
function shuffle(n){const a=Array.from({length:n},(_,i)=>i);for(let i=n-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function ensureAttempt(b,s){const e=s.boss[b.rank]||{attempts:0,history:[]};if(e.activeVariant==null){e.activeVariant=chooseVariant(b,e);e.order=shuffle(b.variants[e.activeVariant].tasks.length);e.current=0;e.damage=0;e.checks=[];e.startedAt=new Date().toISOString()}e.history=e.history||[];s.boss[b.rank]=e;saveSideSystem(s);return e}

function ensureRankPath(){let el=document.getElementById('rankPathPanel');if(el)return el;const root=document.getElementById('sideMissionSystem');if(!root)return null;el=document.createElement('section');el.id='rankPathPanel';el.className='rank-path-panel';const grid=root.querySelector('.side-system-grid');root.insertBefore(el,grid||root.firstChild);return el}
function renderRankPath(){const el=ensureRankPath();if(!el)return;const s=loadSideSystem(),cur=currentClass(s),ci=rankIndex(cur),level=typeof state!=='undefined'?state.level:1;
 const stages=[{rank:'E',level:1,title:'Awakened',boss:'No promotion trial',reward:RANK_REWARDS.E},...BOSS_STAGES.map(b=>({rank:b.rank,level:b.level,title:b.title,boss:b.variants.length+' possible Boss Trials',reward:RANK_REWARDS[b.rank]}))];
 el.innerHTML='<div class="rank-path-head"><div><span class="side-tag">PLAYER PROGRESSION</span><h2>RANK PATH</h2><p>Level '+level+' • Current Rank: '+cur+'-CLASS</p></div><button id="rankPathToggle" type="button">VIEW PATH</button></div><div id="rankPathTrack" class="rank-path-track">'+stages.map((x,i)=>{const cleared=i<ci||(i===0&&ci>0),current=i===ci,locked=i>ci,boss=BOSS_STAGES.find(b=>b.rank===x.rank),entry=boss?s.boss[x.rank]:null,status=cleared?'CLEARED':current?'CURRENT':'LOCKED';return '<article class="rank-node '+(cleared?'cleared ':current?'current ':'locked ')+'"><div class="rank-node-line"></div><div class="rank-emblem">'+x.rank+'</div><div class="rank-node-copy"><span class="side-tag">'+status+'</span><h3>'+x.title+'</h3><p>Level '+x.level+' • '+x.boss+'</p><p>'+x.reward.desc+'</p>'+(entry&&entry.attempts?'<small>'+entry.attempts+' Boss attempt'+(entry.attempts===1?'':'s')+'</small>':'')+'</div></article>'}).join('')+'</div>';
 const btn=document.getElementById('rankPathToggle'),track=document.getElementById('rankPathTrack');btn.onclick=()=>{const open=track.classList.toggle('open');btn.textContent=open?'HIDE PATH':'VIEW PATH'}
}

function adaptiveMissions(){const b=loadBuild(),s=loadSideSystem(),next=nextPromotion(s),weak=next?weakestStats(next.rank)[0]:null,path=TRAINING_PATHS[b.path]||TRAINING_PATHS.Balanced,out=[];
 const pathMap={'Fat Loss':['PATH MISSION','Conditioning Drive','Complete 25–30 minutes of moderate cardio or conditioning.','Conditioning'],'Muscle Building':['PATH MISSION','Hypertrophy Protocol','Complete a resistance session with controlled working sets.','Strength'],Strength:['PATH MISSION','Power Development','Complete a strength-focused resistance session.','Strength'],Endurance:['PATH MISSION','Endurance Base','Complete 25+ minutes of continuous endurance work.','Endurance'],Balanced:['PATH MISSION','Balanced Development','Complete a full-body session combining strength and conditioning.','Consistency']};
 const p=pathMap[b.path]||pathMap.Balanced;out.push({id:'adaptive_path',tag:p[0],title:p[1],desc:p[2],stat:p[3],xp:60});
 if(weak){const d={Strength:'Complete a strength-focused session.',Endurance:'Complete 20+ minutes of steady endurance work.',Conditioning:'Complete a full-body conditioning circuit.',Mobility:'Complete 15 minutes of mobility work.',Consistency:'Complete today’s scheduled training.',Recovery:'Complete 10–15 minutes of recovery or mobility work.'};out.push({id:'adaptive_build',tag:'BUILD MISSION',title:'Develop '+weak.stat,desc:d[weak.stat],stat:weak.stat,xp:50});out.push({id:'adaptive_promo',tag:'PROMOTION MISSION',title:next.rank+'-Class Preparation',desc:'Raise '+weak.stat+' toward '+weak.need+' to satisfy the next promotion standard.',stat:weak.stat,xp:70})}
 const rec=b.stats.Recovery<=Math.min(...BUILD_STATS.filter(x=>x!=='Recovery').map(x=>b.stats[x]));if(rec)out.push({id:'adaptive_recovery',tag:'RECOVERY DIRECTIVE',title:'Recovery Protocol',desc:'Complete light mobility or recovery work. More punishment is not always more progress.',stat:'Recovery',xp:35});
 return out.slice(0,4)}
function completeAdaptiveMission(id){const s=loadSideSystem();s.adaptiveDone=s.adaptiveDone||[];if(s.adaptiveDone.includes(id))return;const m=adaptiveMissions().find(x=>x.id===id);if(!m)return;s.adaptiveDone.push(id);saveSideSystem(s);const b=loadBuild();b.stats[m.stat]=Math.min(100,b.stats[m.stat]+2);saveBuild(b);if(typeof addXp==='function')addXp(m.xp,'adaptive-mission');if(typeof addSystemMessage==='function')addSystemMessage(m.tag+' COMPLETE: '+m.title+' — +'+m.xp+' XP','quest');if(typeof saveState==='function')saveState();if(typeof renderAll==='function')renderAll();renderSideSystem()}
function ensureAdaptivePanel(){let el=document.getElementById('adaptiveMissionPanel');if(el)return el;const root=document.getElementById('sideMissionSystem');if(!root)return null;el=document.createElement('section');el.id='adaptiveMissionPanel';el.className='adaptive-mission-panel';const grid=root.querySelector('.side-system-grid');root.insertBefore(el,grid||null);return el}
function renderAdaptiveMissions(){const el=ensureAdaptivePanel();if(!el)return;const s=loadSideSystem();s.adaptiveDone=s.adaptiveDone||[];const list=adaptiveMissions();el.innerHTML='<div class="adaptive-head"><div><span class="side-tag">SYSTEM GUIDANCE</span><h2>ADAPTIVE MISSIONS</h2><p>Generated from your Training Path, build weaknesses and next promotion.</p></div></div><div class="adaptive-mission-grid">'+list.map(m=>'<article class="adaptive-mission '+(s.adaptiveDone.includes(m.id)?'done':'')+'"><span class="side-tag">'+m.tag+'</span><h3>'+m.title+'</h3><p>'+m.desc+'</p><div><strong>+'+m.xp+' XP</strong><button data-adaptive="'+m.id+'" '+(s.adaptiveDone.includes(m.id)?'disabled':'')+'>'+(s.adaptiveDone.includes(m.id)?'COMPLETE':'CLAIM COMPLETE')+'</button></div></article>').join('')+'</div>';el.querySelectorAll('[data-adaptive]').forEach(x=>x.onclick=()=>completeAdaptiveMission(x.dataset.adaptive))}
function renderSideSystem(){renderPlayerStatus();const root=document.getElementById('sideMissionSystem');if(!root)return;const s=loadSideSystem(),missions=document.getElementById('sideMissionList');renderRankPath();
renderAdaptiveMissions();const available=unlockedMissions(s);missions.innerHTML=available.map(m=>'<article class="side-card '+(s.completed.includes(m.id)?'is-done':'')+'"><div><span class="side-tag">SIDE MISSION</span><h3>'+m.title+'</h3><p>'+m.desc+'</p></div><div class="side-reward">+'+m.xp+' XP</div><button data-side="'+m.id+'" '+(s.completed.includes(m.id)?'disabled':'')+'>'+(s.completed.includes(m.id)?'COMPLETE':'CLAIM COMPLETE')+'</button></article>').join('');
missions.querySelectorAll('[data-side]').forEach(x=>x.onclick=()=>completeSideMission(x.dataset.side));const cls=currentClass(s),reward=RANK_REWARDS[cls]||RANK_REWARDS.E;document.getElementById('currentRankClass').textContent=cls+'-CLASS • '+reward.label;
const wrap=document.getElementById('bossStageList');wrap.innerHTML=BOSS_STAGES.map(b=>{const e=s.boss[b.rank]||{attempts:0,history:[]},best=(e.history||[]).reduce((m,x)=>Math.max(m,x.completed||0),0);
if(e.passed)return '<article class="boss-card boss-passed"><span class="side-tag">BOSS DEFEATED</span><h3>'+b.title+'</h3><p>Promotion achieved • +'+b.reward+' XP</p><button disabled>'+b.rank+'-CLASS UNLOCKED</button></article>';
if(!eligible(b,s)){const level=typeof state!=='undefined'?state.level:1,cm=correctiveMission(b.rank),missing=weakestStats(b.rank);return '<article class="boss-card boss-locked"><span class="side-tag">SYSTEM ANALYSIS</span><h3>'+b.title+'</h3><p>Requires Level '+b.level+(bossIndex(b.rank)>0?' + previous promotion':'')+'. Promotion also requires a balanced build.</p>'+(missing.length?'<div class="build-warning"><strong>UNDERDEVELOPED: '+missing.map(x=>x.stat+' '+x.value+'/'+x.need).join(' • ')+'</strong>'+(cm?'<p>SYSTEM DIRECTIVE: '+cm.desc+'</p>':'')+'</div>':'')+'<button disabled>'+(level<b.level?'LEVEL REQUIREMENT NOT MET':'BUILD STABILIZATION REQUIRED')+'</button></article>'}
return '<article class="boss-card boss-ready"><span class="side-tag">BOSS INTEL</span><h3>'+b.title+'</h3><p>Level '+b.level+' • +'+b.reward+' XP • '+b.variants.length+' possible trials</p><p>Attempts: '+(e.attempts||0)+' • Best: '+best+'/5</p><p>Objectives and order are classified until battle begins.</p><button data-start="'+b.rank+'">'+(e.activeVariant!=null?'RESUME BOSS BATTLE':'BEGIN RANK TRIAL')+'</button></article>'}).join('');
wrap.querySelectorAll('[data-start]').forEach(x=>x.onclick=()=>startBoss(x.dataset.start))}
function completeSideMission(id){const s=loadSideSystem(),m=unlockedMissions(s).find(x=>x.id===id);if(!m||s.completed.includes(id))return;const earned=rewardXp(m.xp,s);s.completed.push(id);saveSideSystem(s);awardBuildMission(id);if(typeof addXp==='function')addXp(earned,'side-mission');if(typeof addSystemMessage==='function')addSystemMessage('Side Mission Complete: '+m.title+' — +'+earned+' XP','quest');if(typeof saveState==='function')saveState();if(typeof renderAll==='function')renderAll();renderSideSystem()}
function startBoss(rank){const b=BOSS_STAGES.find(x=>x.rank===rank),s=loadSideSystem();if(!b||!eligible(b,s))return;ensureAttempt(b,s);openBossBattle(rank)}
function ensureBattleUI(){let el=document.getElementById('bossBattleMode');if(el)return el;el=document.createElement('div');el.id='bossBattleMode';el.className='boss-battle-mode';el.innerHTML='<div class="bb-top"><div><span class="side-tag">SYSTEM • RANK TRIAL</span><h2 id="bbTitle">BOSS STAGE</h2></div><button id="bbExit">✕</button></div><div class="bb-hud"><span id="bbRank"></span><span id="bbAttempt"></span><span id="bbClock">00:00</span></div><div class="bb-hp"><div><span>BOSS HP</span><strong id="bbHpText">100 / 100</strong></div><div class="bb-hp-track"><i id="bbHpBar"></i></div></div><main class="bb-arena"><span id="bbCount" class="side-tag"></span><p id="bbFocus"></p><h1 id="bbObjective"></h1><div id="bbAttack" class="bb-attack"></div><div id="bbTimerPanel" class="bb-timer" hidden><strong id="bbTimer">00:00</strong><button id="bbTimerStart">START TIMER</button></div><button id="bbComplete" class="bb-main">COMPLETE OBJECTIVE</button><button id="bbEnd" class="bb-end">END ATTEMPT</button></main><div id="bbFlash" class="bb-flash"></div>';document.body.appendChild(el);document.getElementById('bbExit').onclick=closeBossBattle;return el}
function openBossBattle(rank){const el=ensureBattleUI();el.dataset.rank=rank;el.classList.add('active');document.body.classList.add('boss-mode-open');battleStartedAt=Date.now();clearInterval(bossClock);bossClock=setInterval(updateBattleClock,1000);renderBossBattle()}
function closeBossBattle(){clearInterval(bossClock);clearInterval(bossTimer);const el=document.getElementById('bossBattleMode');if(el)el.classList.remove('active');document.body.classList.remove('boss-mode-open');renderSideSystem()}
function updateBattleClock(){const e=document.getElementById('bbClock');if(!e)return;const n=Math.floor((Date.now()-battleStartedAt)/1000);e.textContent=fmt(n)}
function fmt(n){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function battleData(){const rank=document.getElementById('bossBattleMode')?.dataset.rank,b=BOSS_STAGES.find(x=>x.rank===rank),s=loadSideSystem(),e=b?s.boss[rank]:null;if(!b||!e||e.activeVariant==null)return null;const v=b.variants[e.activeVariant],order=e.order||v.tasks.map((_,i)=>i),pos=Math.min(e.current||0,order.length-1);return{rank,b,s,e,v,order,obj:v.tasks[order[pos]]}}
function renderBossBattle(){const d=battleData();if(!d){closeBossBattle();return}const{rank,b,e,v,order,obj}=d,hp=Math.max(0,100-(e.damage||0));document.getElementById('bbTitle').textContent=v.name;document.getElementById('bbRank').textContent=rank+'-CLASS AT STAKE';document.getElementById('bbAttempt').textContent='ATTEMPT '+((e.attempts||0)+1);document.getElementById('bbHpText').textContent=hp+' / 100';document.getElementById('bbHpBar').style.width=hp+'%';document.getElementById('bbCount').textContent='OBJECTIVE '+((e.current||0)+1)+' / '+order.length+' REVEALED';document.getElementById('bbFocus').textContent=v.focus;document.getElementById('bbObjective').textContent=obj.text;document.getElementById('bbAttack').textContent=obj.attack+' • '+obj.damage+' DAMAGE';const panel=document.getElementById('bbTimerPanel'),complete=document.getElementById('bbComplete');clearInterval(bossTimer);if(obj.seconds){panel.hidden=false;document.getElementById('bbTimer').textContent=fmt(obj.seconds);document.getElementById('bbTimerStart').textContent='START TIMER';complete.disabled=true;document.getElementById('bbTimerStart').onclick=()=>runObjectiveTimer(obj.seconds)}else{panel.hidden=true;complete.disabled=false}complete.onclick=()=>completeBossObjective(rank);document.getElementById('bbEnd').onclick=()=>endBossAttempt(rank)}
function runObjectiveTimer(seconds){let left=seconds;const btn=document.getElementById('bbTimerStart'),out=document.getElementById('bbTimer'),complete=document.getElementById('bbComplete');btn.disabled=true;bossTimer=setInterval(()=>{left--;out.textContent=fmt(Math.max(0,left));if(left<=0){clearInterval(bossTimer);btn.textContent='TIMER COMPLETE';complete.disabled=false}},1000)}
function completeBossObjective(rank){const d=battleData();if(!d||d.rank!==rank)return;const{b,s,e,v,order,obj}=d;e.damage=(e.damage||0)+obj.damage;e.checks=e.checks||[];e.checks[order[e.current||0]]=true;e.current=(e.current||0)+1;s.boss[rank]=e;saveSideSystem(s);showHit(obj);if(e.current>=order.length){setTimeout(()=>defeatBoss(rank),650)}else setTimeout(renderBossBattle,650)}
function showHit(obj){const f=document.getElementById('bbFlash');if(!f)return;f.textContent=obj.attack+'  -'+obj.damage+' HP';f.classList.remove('hit');void f.offsetWidth;f.classList.add('hit')}
function endBossAttempt(rank){const d=battleData();if(!d||d.rank!==rank)return;const{b,s,e}=d,completed=(e.checks||[]).filter(Boolean).length,damage=e.damage||0;e.attempts=(e.attempts||0)+1;e.history=e.history||[];e.history.push({variant:e.activeVariant,completed,total:5,damage,date:new Date().toISOString(),passed:false});e.lastVariant=e.activeVariant;e.activeVariant=null;e.order=[];e.current=0;e.damage=0;e.checks=[];saveSideSystem(s);if(typeof addSystemMessage==='function')addSystemMessage('BOSS SURVIVED — '+completed+'/5 objectives • '+damage+' damage. Performance recorded.','quest');closeBossBattle();alert('BATTLE ENDED\\n'+completed+'/5 OBJECTIVES\\n'+damage+' DAMAGE DEALT\\nBOSS SURVIVED\\n\\nPOST-BATTLE ANALYSIS\\n'+analyzeBossFailure(rank)+'\\n\\nNext attempt will change.')}
function defeatBoss(rank){const d=battleData();if(!d||d.rank!==rank)return;const{b,s,e}=d;e.attempts=(e.attempts||0)+1;e.history=e.history||[];e.history.push({variant:e.activeVariant,completed:5,total:5,damage:100,date:new Date().toISOString(),passed:true});e.lastVariant=e.activeVariant;e.activeVariant=null;e.order=[];e.current=0;e.damage=0;e.checks=[];e.passed=true;e.passedAt=new Date().toISOString();s.boss[rank]=e;saveSideSystem(s);if(typeof addXp==='function')addXp(b.reward,'boss-stage');if(typeof addSystemMessage==='function')addSystemMessage('BOSS DEFEATED! RANK PROMOTION: '+rank+'-CLASS — +'+b.reward+' XP','level');if(typeof saveState==='function')saveState();if(typeof renderAll==='function')renderAll();const el=ensureBattleUI();el.innerHTML='<div class="bb-victory"><span class="side-tag">SYSTEM ALERT</span><h1>BOSS DEFEATED</h1><p>RANK PROMOTION ACHIEVED</p><div class="bb-new-rank">'+rank+'-CLASS</div><strong>+'+b.reward+' XP</strong><button id="bbVictoryClose" class="bb-main">CONTINUE</button></div>';document.getElementById('bbVictoryClose').onclick=()=>{el.remove();document.body.classList.remove('boss-mode-open');renderSideSystem()}}
if(typeof getRank==='function'){const levelRank=getRank;getRank=function(level){const s=loadSideSystem(),c=currentClass(s);if(c==='E')return levelRank(Math.min(level,9));const b=BOSS_STAGES.find(x=>x.rank===c);return b?levelRank(b.level):levelRank(level)}}
function ensureStatusScreen(){let el=document.getElementById('playerStatusScreen');if(el)return el;const anchor=document.getElementById('playerCard');if(!anchor)return null;el=document.createElement('section');el.id='playerStatusScreen';el.className='status-screen';anchor.insertAdjacentElement('afterend',el);return el}
function nextPromotion(s){const cur=currentClass(s),i=rankIndex(cur);return BOSS_STAGES[i]||null}
function statState(value,need){if(need&&value<need)return'NEEDS ATTENTION';if(value>=70)return'DEVELOPED';return'DEVELOPING'}
function renderPlayerStatus(){const el=ensureStatusScreen();if(!el)return;const b=loadBuild(),s=loadSideSystem(),cur=currentClass(s),next=nextPromotion(s),level=typeof state!=='undefined'?state.level:1,xp=typeof state!=='undefined'?state.xp:0,xpNeed=typeof xpNeededForLevel==='function'?xpNeededForLevel(level):100,req=next?(RANK_STANDARDS[next.rank]||{}):{},met=BUILD_STATS.filter(x=>b.stats[x]>=(req[x]||0)).length,missing=next?weakestStats(next.rank):[],strong=[...BUILD_STATS].sort((a,z)=>b.stats[z]-b.stats[a])[0],weak=[...BUILD_STATS].sort((a,z)=>b.stats[a]-b.stats[z])[0],ready=next?Math.round(BUILD_STATS.reduce((a,x)=>a+Math.min(1,b.stats[x]/Math.max(1,req[x]||1)),0)/BUILD_STATS.length*100):100,dir=next?correctiveMission(next.rank):null;
el.innerHTML='<div class="status-head"><div><span class="side-tag">PLAYER STATUS</span><h2>LEVEL '+level+' • '+cur+'-CLASS</h2><p>Training Path: <strong>'+b.path+'</strong></p><button id="changeTrainingPath" class="path-change" type="button">CHANGE PATH</button></div><div class="status-xp"><span>EXP</span><strong>'+xp+' / '+xpNeed+'</strong></div></div><div class="status-stat-grid">'+BUILD_STATS.map(x=>'<article class="status-stat '+(req[x]&&b.stats[x]<req[x]?'needs':'')+'"><div><strong>'+x+'</strong><span>'+Math.round(b.stats[x])+(next?' / '+req[x]:'')+'</span></div><div class="status-bar"><i style="width:'+Math.min(100,b.stats[x])+'%"></i></div><small>'+statState(b.stats[x],req[x])+'</small></article>').join('')+'</div><div class="status-analysis"><article><span class="side-tag">SYSTEM ANALYSIS</span><p><b>Primary Strength:</b> '+strong+'</p><p><b>Needs Development:</b> '+weak+'</p><p><b>Next Promotion:</b> '+(next?next.rank+'-Class':'MAX RANK')+'</p></article><article><span class="side-tag">BOSS READINESS</span><div class="readiness">'+ready+'%</div><div class="status-bar"><i style="width:'+ready+'%"></i></div><p>'+(next?met+'/6 build requirements met':'All promotion trials cleared')+'</p></article></div><div class="status-directive"><span class="side-tag">SYSTEM DIRECTIVE</span><strong>'+(dir?dir.stat+' requires development.':'BUILD STABILIZED')+'</strong><p>'+(dir?dir.desc:'Maintain your build and continue training.')+'</p></div>';
}
document.getElementById('changeTrainingPath')?.addEventListener('click',openTrainingPathPicker);
}
function openTrainingPathPicker(){let el=document.getElementById('trainingPathPicker');if(!el){el=document.createElement('div');el.id='trainingPathPicker';el.className='path-picker';document.body.appendChild(el)}const current=loadBuild().path;el.innerHTML='<div class="path-picker-card"><div class="path-picker-head"><div><span class="side-tag">SYSTEM • BUILD CONFIGURATION</span><h2>CHOOSE TRAINING PATH</h2><p>Your path guides progression. It never locks your character.</p></div><button id="closePathPicker">✕</button></div><div class="path-options">'+Object.entries(TRAINING_PATHS).map(([key,p])=>'<button class="path-option '+(key===current?'selected':'')+'" data-path="'+key+'"><strong>'+p.label+'</strong><span>'+p.desc+'</span><small>'+(p.boost.length?'FOCUS: '+p.boost.join(' + '):'FOCUS: EVEN DEVELOPMENT')+'</small></button>').join('')+'</div><p class="path-note">Changing paths keeps your Level, XP, Rank, attributes, achievements and workout history.</p></div>';el.classList.add('active');document.getElementById('closePathPicker').onclick=()=>el.classList.remove('active');el.querySelectorAll('[data-path]').forEach(x=>x.onclick=()=>{setTrainingPath(x.dataset.path);el.classList.remove('active')})}
window.renderPlayerStatus=renderPlayerStatus;
function analyzeBossFailure(rank){const missing=weakestStats(rank),c=correctiveMission(rank);if(!missing.length)return 'Build standards met. Continue developing all attributes.';return 'Weakest attribute: '+missing[0].stat+' ('+missing[0].value+'/'+missing[0].need+'). '+(c?'Directive: '+c.desc:'')}
function rankRewardSummary(rank){const r=RANK_REWARDS[rank]||RANK_REWARDS.E;return r.desc}

const ONBOARDING_KEY='systemOnboardingV1';
function onboardingData(){try{return JSON.parse(localStorage.getItem(ONBOARDING_KEY)||'null')}catch(e){return null}}
function onboardingPath(goal){return {'fat-loss':'Fat Loss','muscle':'Muscle Building','strength':'Strength','endurance':'Endurance','balanced':'Balanced'}[goal]||'Balanced'}
function shouldOnboard(){return !!(typeof getCloudSession==='function'&&getCloudSession()?.access_token)&&!onboardingData()}
function showOnboarding(){if(!shouldOnboard())return;let el=document.getElementById('systemOnboarding');if(!el){el=document.createElement('div');el.id='systemOnboarding';el.className='system-onboarding';document.body.appendChild(el)}let step=0,data={name:'',goal:'balanced',experience:'beginner',equipment:[],days:4};const screens=[
 ()=>'<span class="side-tag">CREATE PLAYER • 1/5</span><h1>WHO ARE YOU BECOMING?</h1><p>Set up your player profile. You can change these choices later.</p><input id="obName" class="form-input" placeholder="Player name" value="'+data.name+'">',
 ()=>'<span class="side-tag">PRIMARY GOAL • 2/5</span><h1>CHOOSE YOUR PATH</h1><p>The System will use this to guide your missions.</p><div class="ob-options">'+[['fat-loss','Fat Loss'],['muscle','Muscle Building'],['strength','Strength'],['endurance','Endurance'],['balanced','Balanced Fitness']].map(x=>'<button data-goal="'+x[0]+'" class="'+(data.goal===x[0]?'selected':'')+'">'+x[1]+'</button>').join('')+'</div>',
 ()=>'<span class="side-tag">EXPERIENCE • 3/5</span><h1>TRAINING LEVEL</h1><p>This helps The System keep early missions appropriate.</p><div class="ob-options">'+[['beginner','Beginner'],['intermediate','Intermediate'],['advanced','Advanced']].map(x=>'<button data-exp="'+x[0]+'" class="'+(data.experience===x[0]?'selected':'')+'">'+x[1]+'</button>').join('')+'</div>',
 ()=>'<span class="side-tag">EQUIPMENT • 4/5</span><h1>AVAILABLE GEAR</h1><p>Select everything you can reliably train with.</p><div class="ob-options ob-equipment">'+['Bodyweight','Dumbbells','Barbell','Resistance Bands','Cardio Machine','Full Gym'].map(x=>'<button data-eq="'+x+'" class="'+(data.equipment.includes(x)?'selected':'')+'">'+x+'</button>').join('')+'</div><label class="ob-days">Training days per week <input id="obDays" type="number" min="1" max="7" value="'+data.days+'"></label>',
 ()=>'<span class="side-tag">SYSTEM ANALYSIS • 5/5</span><h1>BUILD ANALYZED</h1><div class="ob-awaken"><small>TRAINING PATH ASSIGNED</small><strong>'+onboardingPath(data.goal)+'</strong><span>E-CLASS AWAKENING</span></div><p>'+data.experience.toUpperCase()+' • '+data.days+' DAYS/WEEK • '+(data.equipment.join(' + ')||'BODYWEIGHT')+'</p>'
];function render(){el.innerHTML='<div class="ob-card">'+screens[step]()+'<div class="ob-actions">'+(step?'<button id="obBack">BACK</button>':'')+'<button id="obNext" class="btn-primary">'+(step===4?'AWAKEN':'CONTINUE')+'</button></div></div>';el.classList.add('active');el.querySelectorAll('[data-goal]').forEach(x=>x.onclick=()=>{data.goal=x.dataset.goal;render()});el.querySelectorAll('[data-exp]').forEach(x=>x.onclick=()=>{data.experience=x.dataset.exp;render()});el.querySelectorAll('[data-eq]').forEach(x=>x.onclick=()=>{data.equipment=data.equipment.includes(x.dataset.eq)?data.equipment.filter(v=>v!==x.dataset.eq):[...data.equipment,x.dataset.eq];render()});document.getElementById('obBack')?.addEventListener('click',()=>{step--;render()});document.getElementById('obNext').onclick=()=>{if(step===0){data.name=(document.getElementById('obName')?.value||'').trim()||'Player'}if(step===3)data.days=Math.max(1,Math.min(7,Number(document.getElementById('obDays')?.value)||4));if(step<4){step++;render();return}const path=onboardingPath(data.goal),b=loadBuild();b.path=path;b.profile={experience:data.experience,equipment:data.equipment,days:data.days};saveBuild(b);localStorage.setItem(ONBOARDING_KEY,JSON.stringify({...data,path,completedAt:new Date().toISOString()}));try{const settings=JSON.parse(localStorage.getItem('theSystemSettings')||'{}');settings.name=data.name;settings.goal=data.goal;localStorage.setItem('theSystemSettings',JSON.stringify(settings))}catch(e){}if(typeof addSystemMessage==='function')addSystemMessage('E-CLASS AWAKENING COMPLETE — '+path+' path assigned.','level');el.classList.remove('active');renderPlayerStatus();renderSideSystem();if(typeof renderAll==='function')renderAll()}}render()}
window.SystemOnboarding={show:showOnboarding,reset:()=>localStorage.removeItem(ONBOARDING_KEY)};
document.addEventListener('DOMContentLoaded',()=>{renderSideSystem();renderPlayerStatus();setTimeout(showOnboarding,250)});
