const {PGlite}=require(process.env.PGLITE_MODULE || '@electric-sql/pglite');const fs=require('fs');const assert=require('assert/strict');
(async()=>{const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;`);
for(const file of fs.readdirSync('supabase/migrations').sort())await db.exec(fs.readFileSync('supabase/migrations/'+file,'utf8').replace('create extension if not exists pgcrypto;',''));
const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002';
await db.exec(`insert into auth.users values('${a}','a@example.com'),('${b}','b@example.com');insert into public.social_profiles(user_id,display_name,xp,level)values('${a}','Alpha',500,10),('${b}','Beta',200,5);insert into public.workout_backups(user_id,data)values('${a}','{"old":true}'),('${b}','{"keep":true}');select set_config('request.jwt.claim.sub','${a}',false);`);
await db.query('select public.reset_my_progress($1::jsonb)',[JSON.stringify({app:'The System - Workout Tracker',localStorage:{the_system_workout_tracker_state:'{"xp":0}'}})]);
let rows=(await db.query('select xp,level from public.social_profiles order by display_name')).rows;assert.deepEqual(rows,[{xp:0,level:1},{xp:200,level:5}]);
assert.equal((await db.query(`select data->>'keep' as kept from public.workout_backups where user_id='${b}'`)).rows[0].kept,'true');
assert.equal((await db.query(`select has_function_privilege('authenticated','public.delete_verified_account(uuid)','EXECUTE') as allowed`)).rows[0].allowed,false);
await db.exec(`select set_config('request.jwt.claim.sub','',false)`);await assert.rejects(db.query('select public.reset_my_progress($1::jsonb)',[JSON.stringify({app:'The System - Workout Tracker',localStorage:{}})]));
// A failure midway through a reset rolls back backup changes as well.
await db.exec(`select set_config('request.jwt.claim.sub','${a}',false);create function public.fail_reset_test() returns trigger language plpgsql as $$begin raise exception 'forced failure';end;$$;create trigger fail_reset_test before update on public.social_profiles for each row execute function public.fail_reset_test();`);
await assert.rejects(db.query('select public.reset_my_progress($1::jsonb)',[JSON.stringify({app:'The System - Workout Tracker',localStorage:{rollback:'must not persist'}})]));
assert.equal((await db.query(`select data->'localStorage'->>'rollback' as value from public.workout_backups where user_id='${a}'`)).rows[0].value,null);
await db.exec('drop trigger fail_reset_test on public.social_profiles;drop function public.fail_reset_test();');
await db.query('select public.delete_verified_account($1::uuid)',[a]);assert.equal((await db.query(`select count(*)::int as n from public.workout_backups where user_id='${a}'`)).rows[0].n,0);assert.equal((await db.query(`select count(*)::int as n from public.social_profiles where user_id='${a}'`)).rows[0].n,0);assert.equal((await db.query('select count(*)::int as n from auth.users')).rows[0].n,1);console.log('PASS: migrations, progress reset, user isolation, authentication, deletion privileges and cascades');await db.close();})().catch(e=>{console.error(e);process.exit(1)});
