const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const AccountData=require('../account-data.js');
function storage(seed={}){const s={...seed};Object.defineProperties(s,{setItem:{value:(k,v)=>s[k]=String(v)},removeItem:{value:k=>delete s[k]},getItem:{value:k=>s[k]??null}});return s;}
const seed={the_system_workout_tracker_state:'old',systemMissionResult_today:'done','systemMissionProgress:today':'sets',systemLegacyTrials:'wins',systemIdentityEarnedV1:'earned',systemWorkoutSessions:'history',systemPlayerBuildV1:JSON.stringify({path:'Strength',profile:{days:4},stats:{Strength:90},assessment:{}}),systemOnboardingV2:JSON.stringify({name:'EJ',days:4,assessmentPending:false}),systemAwakeningAssessmentV1:'assessment',theSystemSettings:'settings',theSystemCloudSession:'session',theSystemRememberMe:'1',theSystemCustomWorkouts:'workouts',systemCustomExercises:'exercises',otherApp:'keep','weeklyWorkoutCredit:today':'1'};
function harness(overrides={}){
 const source=fs.readFileSync(require.resolve('../app.js'),'utf8');
 const code=source.slice(source.indexOf('let accountDataBusy=false;'),source.indexOf('function initSystemSettings()'));
 const el={textContent:'',disabled:false,showModal(){},close(){}};
 const calls=[],local=storage(seed),session=storage({theSystemCloudSession:'session'});
 const context={AccountData,localStorage:local,sessionStorage:session,window:{},document:{getElementById:()=>el,querySelectorAll:()=>[]},location:{reload:()=>calls.push('reload')},confirm:()=>true,prompt:()=> 'RESET',defaultState:()=>({xp:0,level:1,totalXp:0,achievements:[]}),state:{xp:999,weight:{goal:180}},systemBackup:()=>({localStorage:{...local}}),getCloudSession:()=>({user:{id:'user'}}),cloudRequest:async(path,options)=>calls.push({path,options}),...overrides};
 vm.createContext(context);vm.runInContext(code,context);context.accountConfirmation=async(_,word)=>word?context.prompt()===word:context.confirm();return{context,calls,local,session,el};
}
test('Factory Reset clears owned device/session/cache data and never calls cloud',async()=>{const h=harness();const deleted=[];h.context.window.caches={keys:async()=>['the-system-os-v38','other-cache'],delete:async k=>deleted.push(k)};await h.context.factoryResetSystem();assert.deepEqual(Object.keys(h.local),['otherApp']);assert.equal(Object.keys(h.session).length,0);assert.deepEqual(deleted,['the-system-os-v38']);assert.deepEqual(h.calls,['reload']);});
test('Factory Reset cancellation and cache failure keep data',async()=>{const h=harness({confirm:()=>false});await h.context.factoryResetSystem();assert.equal(h.local.theSystemCloudSession,'session');h.context.confirm=()=>true;h.context.window.caches={keys:async()=>{throw Error('cache failed')}};await h.context.factoryResetSystem();assert.equal(h.local.the_system_workout_tracker_state,'old');assert.deepEqual(h.calls,[]);});
test('Reset Progress resets all progression, preserves account/settings/custom library and schedules assessment',async()=>{const h=harness();await h.context.resetTrainingData();assert.equal(h.calls[0].path,'/rest/v1/rpc/reset_my_progress');assert.equal(h.local.theSystemCloudSession,'session');assert.equal(h.local.theSystemSettings,'settings');assert.equal(h.local.theSystemCustomWorkouts,'workouts');assert.equal(h.local.systemCustomExercises,'exercises');assert.equal(h.local.otherApp,'keep');for(const k of ['systemLegacyTrials','systemIdentityEarnedV1','systemAwakeningAssessmentV1','systemMissionProgress:today','systemWorkoutSessions','weeklyWorkoutCredit:today'])assert.equal(h.local[k],undefined,k);assert.equal(JSON.parse(h.local.systemOnboardingV2).assessmentPending,true);assert.equal(JSON.parse(h.local.the_system_workout_tracker_state).xp,0);assert.equal(JSON.parse(h.local.systemPlayerBuildV1).path,'Strength');const payload=JSON.parse(h.calls[0].options.body);assert.equal(payload.replacement.localStorage.theSystemCloudSession,undefined);assert.equal(payload.replacement.localStorage.otherApp,undefined);});
test('Reset Progress wrong confirmation and cloud failure leave progression intact',async()=>{const h=harness({prompt:()=> 'reset'});await h.context.resetTrainingData();assert.equal(h.local.systemLegacyTrials,'wins');h.context.prompt=()=> 'RESET';h.context.cloudRequest=async()=>{throw Error('offline')};await h.context.resetTrainingData();assert.equal(h.local.the_system_workout_tracker_state,'old');assert.equal(h.local.systemAwakeningAssessmentV1,'assessment');assert.equal(h.el.textContent,'offline');});
test('Delete Account posts password and DELETE only to its endpoint, then clears device',async()=>{const h=harness();let cleared=false;const event={preventDefault(){},currentTarget:{elements:{password:{value:'secret'},confirmation:{value:'DELETE'}},reset(){cleared=true}}};await h.context.submitDeleteAccount(event);assert.equal(h.calls[0].path,'/functions/v1/delete-account');assert.deepEqual(JSON.parse(h.calls[0].options.body),{password:'secret',confirmation:'DELETE'});assert.equal(cleared,true);assert.deepEqual(Object.keys(h.local),['otherApp']);});
test('Delete Account failure and incorrect confirmation preserve local data',async()=>{const h=harness({cloudRequest:async()=>{throw Error('Password verification failed.')}});const event={preventDefault(){},currentTarget:{elements:{password:{value:'wrong'},confirmation:{value:'DELETE'}},reset(){throw Error('should not reset')}}};await h.context.submitDeleteAccount(event);assert.equal(h.local.theSystemCloudSession,'session');assert.equal(h.local.systemWorkoutSessions,'history');event.currentTarget.elements.confirmation.value='delete';await h.context.submitDeleteAccount(event);assert.equal(h.local.the_system_workout_tracker_state,'old');});
test('delete endpoint verifies same account before service-role deletion',async()=>{const {createDeleteHandler}=await import('../supabase/functions/delete-account/handler.mjs');const calls=[];const responses=[new Response(JSON.stringify({id:'u1',email:'user@example.com'})),new Response(JSON.stringify({user:{id:'u1'}})),new Response('{}')];const handler=createDeleteHandler({url:'https://test',anonKey:'public',serviceKey:'private',fetcher:async(url,opts)=>{calls.push({url,opts});return responses.shift()}});const response=await handler(new Request('https://test',{method:'POST',headers:{Authorization:'Bearer token'},body:JSON.stringify({password:'secret',confirmation:'DELETE'})}));assert.equal(response.status,200);assert.equal(calls.length,3);assert.equal(calls[2].opts.headers.Authorization,'Bearer private');assert.deepEqual(JSON.parse(calls[2].opts.body),{target_user:'u1'});});
test('delete endpoint rejects bad password, wrong account, missing session, confirmation and server failure',async()=>{const {createDeleteHandler}=await import('../supabase/functions/delete-account/handler.mjs');for(const scenario of ['password','identity','session','confirmation','server']){let calls=0;const handler=createDeleteHandler({url:'https://test',anonKey:'a',serviceKey:'s',fetcher:async()=>{calls++;if(calls===1)return new Response(JSON.stringify({id:'u',email:'u@example.com'}));if(calls===2)return new Response(JSON.stringify({user:{id:scenario==='identity'?'other':'u'}}),{status:scenario==='password'?401:200});return new Response('{}',{status:503})}});const response=await handler(new Request('https://test',{method:'POST',headers:scenario==='session'?{}:{Authorization:'Bearer token'},body:JSON.stringify({password:'wrong',confirmation:scenario==='confirmation'?'delete':'DELETE'})}));assert.equal(response.status,scenario==='server'?503:scenario==='identity'?403:scenario==='confirmation'?400:401);assert.equal(calls,scenario==='session'||scenario==='confirmation'?0:scenario==='server'?3:2);}});
test('confirmation dialog handles exact RESET, Cancel and Escape separately',async()=>{
 const source=fs.readFileSync(require.resolve('../app.js'),'utf8');const code=source.slice(source.indexOf('function accountConfirmation('),source.indexOf('async function runAccountOperation'));
 const input={value:''},form={elements:{confirmation:input}},button={},message={},label={};const dialog={open:false,showModal(){this.open=true},close(){this.open=false}};const elements={accountConfirmDialog:dialog,accountConfirmForm:form,accountConfirmMessage:message,accountConfirmLabel:label,cancelAccountConfirm:button};const ctx={accountDataBusy:false,document:{getElementById:id=>elements[id]}};vm.createContext(ctx);vm.runInContext(code,ctx);
 let result=ctx.accountConfirmation('Reset training','RESET');input.value='RESET';form.onsubmit({preventDefault(){}});assert.equal(await result,true);assert.equal(dialog.open,false);
 result=ctx.accountConfirmation('Reset training','RESET');input.value='reset';form.onsubmit({preventDefault(){}});assert.equal(await result,false);
 result=ctx.accountConfirmation('Factory Reset');button.onclick();assert.equal(await result,false);
 result=ctx.accountConfirmation('Reset training','RESET');dialog.oncancel({preventDefault(){}});assert.equal(await result,false);
});
